---
# tasks file for molecule_http_docker_demo
- name: Pull nginx docker image
  community.docker.docker_image:
    name: "{{ nginx_image }}"
    source: pull
    force_source: true

- name: Start start nginx service via Docker
  community.general.docker_container:
    name: "{{ nginx_service_name }}"
    image: "{{ nginx_image }}"
    published_ports: "{{ nginx_ports }}"
    mounts: "{{ nginx_mounts }}"
    command: "{{ nginx_cli_commands }}"
    labels: "{{ nginx_labels }}"
    comparisons:
      '*': strict
      labels: allow_more_present
    restart_policy: unless-stopped
