---
dependency:
  name: galaxy
  requirements-file: requirements.yml

driver:
  name: vagrant

platforms:
  - name: instance
    box: debian/bullseye64

provisioner:
  name: ansible

verifier:
  name: ansible
